### ISSUE TITLE
Question about the target of imputation

### ISSUE THREAD

**Issue by packer-c** [LMZZML/PriSTI#1]
Thanks for your interesting work.
Could you please answer a question for me?
I noticed that in the paper you mentioned "Block missing: based on randomly masking 5% of the observed data. And Point missing: randomly mask 25% of observations"
My question is how to get table 3, METR-LA: Block-missing (16.6%) Point-missing (31.1%); PEMS-BAY: Block-missing (9.2%) Point-missing (25.0%). How is it calculated the missing rates in your code?

Looking forward to your reply, thanks a lot!

**Comment by LMZZML** [comment]
The missing rates of the datasets in Table 3 includes two parts: the original missing of the dataset and the missing we imposed for evaluation. Taking the block-missing pattern of METR-LA as an example, the original METR-LA dataset has 8.1% missing, and we have added 8.5% missing through the sample_mask() function, so the total missing rate is 16.6%, which is marked in Table 3.
In our code, you can directly calculate the proportion of 0 elements in {ob_mask}, {eval_mask} and {gt_mask} in dataset_{data_name}.py, i.e., the missing rate of data. 
Hope we can answer your doubts.

**Comment by packer-c** [comment]
> The missing rates of the datasets in Table 3 includes two parts: the original missing of the dataset and the missing we imposed for evaluation. Taking the block-missing pattern of METR-LA as an example, the original METR-LA dataset has 8.1% missing, and we have added 8.5% missing through the sample_mask() function, so the total missing rate is 16.6%, which is marked in Table 3. In our code, you can directly calculate the proportion of 0 elements in {ob_mask}, {eval_mask} and {gt_mask} in dataset_{data_name}.py, i.e., the missing rate of data. Hope we can answer your doubts.

Thank you for your kind reply.
I printed these mask value and got the result of Table 3. 

so our imputation target is all missing values (including original missing and manually added missing value. 
Manually added missing value will be evaluated, and original missing value will not be evaluated since there are no ground truth. Right?

**Comment by LMZZML** [comment]
Yes. We only can evaluate on the manually added missing values.

**Comment by packer-c** [comment]
I understand. Thanks a lot!
