### ISSUE TITLE
关于消融实验的问题

### ISSUE THREAD

**Issue by xzscode** [LMZZML/PriSTI#3]
需要怎么复现你文章中的那几个消融实验，是不是有些可以通过设置超参来完成，比如is_unconditional？

**Comment by LMZZML** [comment]
is_unconditional是不用改的；在消融实验中，mix-STI可以通过将use_guide、is_cross_s、is_cross_t都设置为false实现，w/o CF可以通过将is_cross_s、is_cross_t设置为false实现；剩余的变体需要在forward中删除对应模块。

**Comment by xzscode** [comment]
非常感谢您的回答！我还有一个问题是当我尝试在evalue中添加mape这项指标时,我的理解是最后的数据都只做了c_data = ((df.fillna(0).values - self.train_mean) / self.train_std的放缩处理，我实际计算只需要通过mape_current=torch.abs(((samples_median.values+mean_scaler)/(c_target+mean_scaler))-1) * eval_points * 100放缩回去即可，但是结果mape异常的小（0.1%左右）我想问一下samples_median.values，c_target是有经过其他的处理吗

**Comment by LMZZML** [comment]
没有其他的处理了，只有normalization。如果你计算MAPE是你提供的代码这样写的话，应该是你式子写错了，应该samples_median和c_target都要分别乘scaler再加上mean_scaler后再相除；如果还有问题可以print你填补且denormalization后得到的结果查看一下。

**Comment by xzscode** [comment]
式子的问题已经得到解决，非常感谢！之前的计算是先通过化简得到的最简形式，估计是程序运行有问题，这次把原来的公式打进去，数据看起来是正常的了，再次感谢！
