### ISSUE TITLE
关于确定插补/概率插补的问题

### ISSUE THREAD

**Issue by Zjh152** [LMZZML/PriSTI#4]
作者你好，这篇论文非常优秀，让我受益匪浅，我有几个问题想咨询作者。
第一，PriSTI是一个概率插补模型，如何与其他确定插补模型进行MAE、MSE的比较，是将概率插补的中位数视为一个确定插补值吗？
第二，如何获取插补后的数据以便进行可视化研究。
感谢作者。

**Comment by LMZZML** [comment]
感谢你对我们工作的认可。对于你提出的问题，回复如下：
A1：是的。在文中有提到，将概率填补的中位数作为确定填补的结果与其他方法进行比较。
A2：在inference过程结束后，会在./save目录的对应文件夹下，生成当前的填补结果文件generated_outputs_nsample{nsample}.pk。其中的内容请参考utils.py中的evaluate()方法（第162行前后）。该文件中包含了所有生成的填补结果样本和其对应的各种mask，可采用torch.quantile方法获取不同分位数的填补结果，并对样本分布进行可视化分析。

**Comment by Zjh152** [comment]
十分感谢
