### ISSUE TITLE
关于训练过程中meta-la显存占用过大问题

### ISSUE THREAD

**Issue by xzscode** [LMZZML/PriSTI#5]
你好，我还有一个问题是训练metr-la过程中显存的占用达到了25000多mb，相比较下pems-bay训练只占了4000多，训练时间metr-la也花费很长时间（好几天）。我想问一下您当时训练过程中有出现这种情况吗？

**Comment by LMZZML** [comment]
并不会。Metr-la在节点和时间规模上都比pems-bay小，建议检查一下batch_size是否设置的过大，或者调整./config/traffic.yaml中的proj_t参数，尽管过小将会影响模型性能，但也可以减少参数量。

**Comment by xzscode** [comment]
最终发现问题可能是出在GPU上，切换了Tesla V100-PCIE跑就没问题，而在NVIDIA RTX A6000就会有异常。。。
