### ISSUE TITLE
关于Sensitivity analysis(RQ2)实验问题

### ISSUE THREAD

**Issue by Zjh152** [LMZZML/PriSTI#6]
作者你好，我想询问
1.在Sensitivity analysis(RQ2)实验中，missing rate从10%到90%是通过修改哪个参数实现的？
2.缺失率都是指整个数据集的缺失率吗？如Table III，METR-LA,Block-missing(16.6%)，Point-missing（31.1%）。
感谢

**Comment by Zjh152** [comment]
我似乎明白了这个问题，缺失率通过missing_ratio控制，但是missing_ratio仅在测试集中进行缺失值的生成。
我不是CS专业的学生，我的问题可能显得有些愚蠢，还请作者谅解。

**Comment by GRAPH-0** [comment]
That is okay, feel free to open the issue.
