### ISSUE TITLE
实验细节的一些问题

### ISSUE THREAD

**Issue by JeremyChou28** [LMZZML/PriSTI#8]
您好，非常感谢您的工作。
关于https://github.com/LMZZML/PriSTI/issues/6，我也有相同的问题。
missing_ratio针对的应该是整个数据集上的缺失率吧？而不仅仅是测试集上的？

**Comment by JeremyChou28** [comment]
另外，我还想请教一个问题
您还在补全后的数据集上评价了预测任务的性能。您这里是拿补全后的数据集替代了原始数据集去评价预测性能。
这里我想确认一下我理解的是否正确？
这里的补全指的是把metrla，pemsbay的天然缺失位置的值补全，然后在这上面做预测任务。ori指的是直接在这些数据集上（包含天然的缺失）预测的性能。

**Comment by LMZZML** [comment]
（1）如果你说的是我们文章中表3所标记的缺失率，那就是整个数据集上的缺失率；更具体的可以参考Filling the g_ap_s: Multivariate time series imputation by graph neural networks；
（2）你的理解是正确的。我们文章给出了在AQI-36数据集上的结果，在metrla和pemsbay上也可以做同样的实验。

**Comment by JeremyChou28** [comment]
> （1）如果你说的是我们文章中表3所标记的缺失率，那就是整个数据集上的缺失率；更具体的可以参考Filling the g_ap_s: Multivariate time series imputation by graph neural networks； （2）你的理解是正确的。我们文章给出了在AQI-36数据集上的结果，在metrla和pemsbay上也可以做同样的实验。

谢谢您的回复，除了表3中的缺失率，关于sensitivity study中的fig5，在METRLA的不同缺失率下的结果。
这里的实验结果是指整个数据集缺失率为10%-90%下，重新训练并在测试集上计算得到的结果，还是说直接用表3中缺失率训练的模型在缺失率为10%-90%的测试集上进行测试的结果呢？

**Comment by LMZZML** [comment]
不需要为每个不同的缺失率单独训练模型，直接使用表3中的模型在不同的缺失率下进行测试即可。
