### ISSUE TITLE
关于所给的预训练权重文件

### ISSUE THREAD

**Issue by HarperHao** [LMZZML/PriSTI#9]
非常好的工作！也非常感谢您公开了预训练权重文件！

在使用代码过程中我遇到了一个问题，请问所给的交通数据权重文件是点缺失还是块缺失呢？

**Comment by LMZZML** [comment]
感谢您对我们工作的认可。所给的用于交通数据集的模型文件是block-missing模式下的。

**Comment by HarperHao** [comment]
感谢您的回答！
